"""phase 1 integrated copilot foundation

Revision ID: a7d55591fe7d
Revises: 20261001_0001
Create Date: 2026-10-01 21:44:42.454336
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'a7d55591fe7d'
down_revision: Union[str, None] = '20261001_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('conexiones_ehr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('proveedor', sa.String(length=80), nullable=False),
    sa.Column('fhir_base_url', sa.String(length=500), nullable=False),
    sa.Column('client_id', sa.String(length=150), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conexiones_ehr_organizacion_id'), 'conexiones_ehr', ['organizacion_id'], unique=False)
    op.create_table('eventos_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('recurso_tipo', sa.String(length=80), nullable=False),
    sa.Column('recurso_id', sa.String(length=80), nullable=True),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auditoria_org_created', 'eventos_auditoria', ['organizacion_id', 'created_at'], unique=False)
    op.create_table('membresias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'medico', 'auditor', name='rolmembresia'), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'medico_id', name='uq_membresia_org_medico')
    )
    op.create_index(op.f('ix_membresias_medico_id'), 'membresias', ['medico_id'], unique=False)
    op.create_index(op.f('ix_membresias_organizacion_id'), 'membresias', ['organizacion_id'], unique=False)
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizacion_id', 'nombre', name='uq_sede_org_nombre')
    )
    op.create_index(op.f('ix_sedes_organizacion_id'), 'sedes', ['organizacion_id'], unique=False)
    op.create_table('consentimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('otorgado', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consentimientos_org_paciente', 'consentimientos', ['organizacion_id', 'paciente_id'], unique=False)
    op.create_table('smart_launches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajos_procesamiento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('creado', 'transcribiendo', 'estructurando', 'listo', 'fallido', name='estadotrabajo'), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.Column('resultado', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trabajos_org_created', 'trabajos_procesamiento', ['organizacion_id', 'created_at'], unique=False)
    op.create_table('versiones_historia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('historia_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('s_subjetivo', sa.Text(), nullable=True),
    sa.Column('o_objetivo', sa.Text(), nullable=True),
    sa.Column('a_analisis', sa.Text(), nullable=True),
    sa.Column('p_plan', sa.Text(), nullable=True),
    sa.Column('receta', sa.JSON(), nullable=True),
    sa.Column('motivo_cambio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['historia_id'], ['historias_clinicas.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('historia_id', 'version', name='uq_historia_version')
    )
    op.create_index('ix_versiones_org_historia', 'versiones_historia', ['organizacion_id', 'historia_id'], unique=False)
    op.add_column('citas', sa.Column('organizacion_id', sa.Integer(), nullable=True))
    op.drop_index('ix_citas_medico_fecha', table_name='citas')
    op.create_index('ix_citas_org_fecha', 'citas', ['organizacion_id', 'fecha_hora'], unique=False)
    op.create_index(op.f('ix_citas_organizacion_id'), 'citas', ['organizacion_id'], unique=False)
    op.create_foreign_key(None, 'citas', 'organizaciones', ['organizacion_id'], ['id'])
    op.add_column('historias_clinicas', sa.Column('organizacion_id', sa.Integer(), nullable=True))
    estado_nota = postgresql.ENUM(
        'borrador', 'firmada', 'enmendada', name='estadonota', create_type=False
    )
    estado_nota.create(op.get_bind(), checkfirst=True)
    op.add_column('historias_clinicas', sa.Column('estado', estado_nota, nullable=True))
    op.add_column('historias_clinicas', sa.Column('version_actual', sa.Integer(), nullable=True))
    op.add_column('historias_clinicas', sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_historias_medico_created', table_name='historias_clinicas')
    op.create_index(op.f('ix_historias_clinicas_organizacion_id'), 'historias_clinicas', ['organizacion_id'], unique=False)
    op.create_index('ix_historias_org_created', 'historias_clinicas', ['organizacion_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'historias_clinicas', 'organizaciones', ['organizacion_id'], ['id'])
    op.add_column('pacientes', sa.Column('organizacion_id', sa.Integer(), nullable=True))
    op.alter_column('pacientes', 'medico_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_paciente_medico_documento', 'pacientes', type_='unique')
    op.create_index(op.f('ix_pacientes_organizacion_id'), 'pacientes', ['organizacion_id'], unique=False)
    op.create_unique_constraint('uq_paciente_org_documento', 'pacientes', ['organizacion_id', 'documento'])
    op.create_foreign_key(None, 'pacientes', 'organizaciones', ['organizacion_id'], ['id'])
    # Preserve prototype data by assigning one temporary organization per existing doctor.
    op.execute("""
        INSERT INTO organizaciones (nombre, slug, activa)
        SELECT 'Consultorio de ' || nombre, 'legacy-' || id, true FROM medicos
    """)
    op.execute("""
        INSERT INTO membresias (organizacion_id, medico_id, rol, activa)
        SELECT o.id, m.id, 'admin', true
        FROM medicos m JOIN organizaciones o ON o.slug = 'legacy-' || m.id
    """)
    op.execute("""
        UPDATE pacientes p SET organizacion_id = o.id
        FROM organizaciones o WHERE o.slug = 'legacy-' || p.medico_id
    """)
    op.execute("""
        UPDATE citas c SET organizacion_id = o.id
        FROM organizaciones o WHERE o.slug = 'legacy-' || c.medico_id
    """)
    op.execute("""
        UPDATE historias_clinicas h
        SET organizacion_id = o.id, estado = 'borrador', version_actual = 1
        FROM organizaciones o WHERE o.slug = 'legacy-' || h.medico_id
    """)
    op.execute("""
        INSERT INTO versiones_historia (
            organizacion_id, historia_id, version, autor_id,
            s_subjetivo, o_objetivo, a_analisis, p_plan, receta
        )
        SELECT organizacion_id, id, 1, medico_id,
               s_subjetivo, o_objetivo, a_analisis, p_plan, receta
        FROM historias_clinicas
    """)
    op.alter_column('pacientes', 'organizacion_id', nullable=False)
    op.alter_column('citas', 'organizacion_id', nullable=False)
    op.alter_column('historias_clinicas', 'organizacion_id', nullable=False)
    op.alter_column('historias_clinicas', 'estado', nullable=False)
    op.alter_column('historias_clinicas', 'version_actual', nullable=False)

    tenant_tables = (
        'pacientes', 'citas', 'historias_clinicas', 'versiones_historia',
        'consentimientos', 'trabajos_procesamiento', 'eventos_auditoria',
        'conexiones_ehr', 'smart_launches', 'sedes'
    )
    for table in tenant_tables:
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY')
        op.execute(f"""
            CREATE POLICY {table}_tenant_policy ON {table}
            USING (
                organizacion_id = NULLIF(current_setting('app.current_organization_id', true), '')::integer
            )
            WITH CHECK (
                organizacion_id = NULLIF(current_setting('app.current_organization_id', true), '')::integer
            )
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pacientes', type_='foreignkey')
    op.drop_constraint('uq_paciente_org_documento', 'pacientes', type_='unique')
    op.drop_index(op.f('ix_pacientes_organizacion_id'), table_name='pacientes')
    op.create_unique_constraint('uq_paciente_medico_documento', 'pacientes', ['medico_id', 'documento'], postgresql_nulls_not_distinct=False)
    op.alter_column('pacientes', 'medico_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pacientes', 'organizacion_id')
    op.drop_constraint(None, 'historias_clinicas', type_='foreignkey')
    op.drop_index('ix_historias_org_created', table_name='historias_clinicas')
    op.drop_index(op.f('ix_historias_clinicas_organizacion_id'), table_name='historias_clinicas')
    op.create_index('ix_historias_medico_created', 'historias_clinicas', ['medico_id', 'created_at'], unique=False)
    op.drop_column('historias_clinicas', 'signed_at')
    op.drop_column('historias_clinicas', 'version_actual')
    op.drop_column('historias_clinicas', 'estado')
    postgresql.ENUM(name='estadonota').drop(op.get_bind(), checkfirst=True)
    op.drop_column('historias_clinicas', 'organizacion_id')
    op.drop_constraint(None, 'citas', type_='foreignkey')
    op.drop_index(op.f('ix_citas_organizacion_id'), table_name='citas')
    op.drop_index('ix_citas_org_fecha', table_name='citas')
    op.create_index('ix_citas_medico_fecha', 'citas', ['medico_id', 'fecha_hora'], unique=False)
    op.drop_column('citas', 'organizacion_id')
    op.drop_index('ix_versiones_org_historia', table_name='versiones_historia')
    op.drop_table('versiones_historia')
    op.drop_index('ix_trabajos_org_created', table_name='trabajos_procesamiento')
    op.drop_table('trabajos_procesamiento')
    op.drop_table('smart_launches')
    op.drop_index('ix_consentimientos_org_paciente', table_name='consentimientos')
    op.drop_table('consentimientos')
    op.drop_index(op.f('ix_sedes_organizacion_id'), table_name='sedes')
    op.drop_table('sedes')
    op.drop_index(op.f('ix_membresias_organizacion_id'), table_name='membresias')
    op.drop_index(op.f('ix_membresias_medico_id'), table_name='membresias')
    op.drop_table('membresias')
    op.drop_index('ix_auditoria_org_created', table_name='eventos_auditoria')
    op.drop_table('eventos_auditoria')
    op.drop_index(op.f('ix_conexiones_ehr_organizacion_id'), table_name='conexiones_ehr')
    op.drop_table('conexiones_ehr')
    op.drop_table('organizaciones')
    # ### end Alembic commands ###
